# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.41.0"

default_platform :android

platform :android do

  desc "Clean everything"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build the SDK"
  lane :build_sdk do
    gradle(task: "assembleRelease")
    if is_ci
      sh "cp -r $BUILD_DIR/sdk/build/outputs $CIRCLE_ARTIFACTS"
    end
  end

  desc "Deploy a new version as the Release"
  lane :distribute_release do
    ## Prerequesties
    build_sdk
    archive_file = sdk_path

    ## Create Github Release
    release_name = version_code
    set_git_identity_when_needed
    github_release = set_github_release(
      repository_name: 'moneytree/mt-link-android-sdk-example',
      name: "v#{release_name}",
      tag_name: "v#{release_name}",
      description: "<TBD>",
      upload_assets: [archive_file]
    )

    UI.message("Release: #{github_release}.".yellow)
  end

  ### Private lanes ###
  private_lane :set_git_identity_when_needed do
    if is_ci
      sh 'git config user.name "MTService"'
      sh 'git config user.email "support@moneytree.jp"'
    end
  end

  def sdk_path
    version = version_code
    if is_ci
      result = Actions.sh("echo $BUILD_DIR/app/libs/MoneytreeLinkCore-#{version}.aar")
    else
      result = Actions.sh("echo #{File.expand_path("..", Dir.pwd)}/app/libs/MoneytreeLinkCore-#{version}.aar")
    end
    result.strip
  end

  def version_code
    # Extract from aar package because the example should have the same number.
    if is_ci
      result = Actions.sh("find $BUILD_DIR/app/libs -type f -regex '.*aar' | sed -r 's/.*-(.*).aar/\\1/'")
    else
      result = Actions.sh("find ../app/libs -type f -regex '.*aar' | sed -r 's/.*-(.*).aar/\\1/'")
    end
    result.strip
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
