fastlane_version "2.101.1"

default_platform :android
platform :android do

  desc "Make new release item on github"
  lane :make_new_release do |options|
    if !options.has_key?(:version)
      UI.error "version is required. Aborted."
      next
    end

    version = options[:version]
    release_assets = [
      "app/libs/MoneytreeLinkCore-#{version}.aar",
      "app/libs/MoneytreeLinkIsshoTsucho-#{version}.aar",
      "MoneytreeLinkCore-Javadoc.zip",
      "MoneytreeLinkIsshoTsucho-Javadoc.zip"
    ]
    example_github_release = set_github_release(
      repository_name: "moneytree/mt-link-android-sdk-example",
      name: "#{version}",
      tag_name: "#{version}",
      description: "#{version}",
      upload_assets: release_assets
    )

    UI.message "Released #{example_github_release}".yellow
  end
end
